name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.github.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header

          # Templete
          template: classic

          # Uhhhhh...
          plugin_lines: yes

          # Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Most used languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, batchfile, makefile, qmake, lex, cmake, gnuplot, vue, scala, ejs
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 10
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

          # Notable
          plugin_notable: yes
          plugin_notable_repositories: no

          # Starred topics
          plugin_topics: yes
          plugin_topics_sort: stars    
          plugin_topics_mode: mastered
          plugin_topics_limit: 0      

          # Achievements
          plugin_achievements: yes
          plugin_achievements_secrets: yes 
          plugin_achievements_limit: 0          

          # Order
          config_order: base.header, lines, isocalendar, languages, notable, topics, achievements